### ISSUE TITLE
Pipelines failing because of lack of resources

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#12]
##### There are customers are directly impacted by this bug? Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug

Some of the pipelines are failing because they don't have enough resources to run.

##### Log Errors
-------------------------------------------
```shell
Driver stacktrace:
22/11/22 00:05:17 INFO DAGScheduler: Job 0 failed: load at NativeMethodAccessorImpl.java:0, took 553.231508 s
22/11/22 00:05:17 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[31m[1m[32m2022-11-22 00:05:17.226[0m[31m[1m[0m  [31m[1mERROR     [0m  [31m[1m[36mdadosfera_logs.dadosfera_logger[0m[31m[1m[0m  [31m[1mUncaught exception: An error occurred while calling o50.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.OutOfMemoryError: Java heap space
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2023)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1972)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1971)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1971)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:950)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2203)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:752)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2093)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2133)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.bulkListLeafFiles(InMemoryFileIndex.scala:240)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.listLeafFiles(InMemoryFileIndex.scala:135)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.refresh0(InMemoryFileIndex.scala:98)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:70)
	at org.apache.spark.sql.execution.datasources.DataSource.createInMemoryFileIndex(DataSource.scala:561)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:399)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.createBaseDataset(JsonDataSource.scala:124)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.infer(JsonDataSource.scala:97)
	at org.apache.spark.sql.execution.datasources.json.JsonDataSource.inferSchema(JsonDataSource.scala:65)
	at org.apache.spark.sql.execution.datasources.json.JsonFileFormat.inferSchema(JsonFileFormat.scala:61)
	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:193)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:190)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:401)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
[0m
[33m[1mTraceback (most recent call last):[0m
> File "[32m/app/[0m[32m[1mmain.py[0m", line [33m175[0m, in [35m<module>[0m
    [1mprint[0m[1m([0m[1mmain[0m[1m([0m[1mconfig[0m[1m,[0m [1mlogger[0m[1m)[0m[1m)[0m
  File "[32m/app/[0m[32m[1mmain.py[0m", line [33m129[0m, in [35mmain[0m
    [1mdata_frame[0m [35m[1m=[0m [1mspark_s3_collector_uc[0m[35m[1m.[0m[1mexecute_full_load[0m[1m([0m[1m)[0m
  File "[32m/app/core/[0m[32m[1musecase.py[0m", line [33m82[0m, in [35mexecute_full_load[0m
    [1mdata_frame[0m [35m[1m=[0m [1mself[0m[35m[1m.[0m[1ms3_engine[0m[35m[1m.[0m[1mread[0m[1m([0m[1mpath[0m[1m)[0m
  File "[32m/app/core/readers/[0m[32m[1ms3_reader.py[0m", line [33m73[0m, in [35mread[0m
    [35m[1mreturn[0m [1mself[0m[35m[1m.[0m[1mreader[0m[35m[1m.[0m[1mread_file[0m[1m([0m[1mpath_or_paths[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mparams[0m[1m)[0m
  File "[32m/app/core/readers/[0m[32m[1mjson_reader.py[0m", line [33m68[0m, in [35mread_file[0m
    [35m[1mreturn[0m [1mself[0m[35m[1m.[0m[1mreader[0m[35m[1m.[0m[1mload[0m[1m([0m[1mpath_or_paths[0m[1m)[0m
  File "[32m/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/[0m[32m[1mreadwriter.py[0m", line [33m178[0m, in [35mload[0m
  File "[32m/opt/bitnami/spark/python/lib/py4j-0.10.9-src.zip/py4j/[0m[32m[1mjava_gateway.py[0m", line [33m1305[0m, in [35m__call__[0m
  File "[32m/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/[0m[32m[1mutils.py[0m", line [33m131[0m, in [35mdeco[0m
  File "[32m/opt/bitnami/spark/python/lib/py4j-0.10.9-src.zip/py4j/[0m[32m[1mprotocol.py[0m", line [33m328[0m, in [35mget_return_value[0m
[31m[1mpy4j.protocol.Py4JJavaError[0m:[1m An error occurred while calling o50.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.OutOfMemoryError: Java heap space
Driver stacktrace:
```

##### This bug impact any demo or a sales?
-------------------------------------------

#### Dadosfera Customer:
-------------------------------------------
- elvenworks

#### Pipeline Ids:
- fcea9bb4_8df8_4c7e_85a1_1c3420079b68

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@rafaelsantanaep do you suggest something to resolve this?

**Comment by rafaelsantanaep** [comment]
For now, I think we will have to deal with this on a case-by-case basis, increasing the amount of memory and CPU available for a job that is failing. In the future, we may have to gather some metadata about the job to "predict" the amount of memory and CPU before the job starts, but this is very complicated for data collected from APIs.
