### ISSUE TITLE
java.sql.SQLException: Zero date value prohibited

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#15]
##### There are customers directly impacted by this bug. Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

### Useful information:
- `connector`: jdbc
- `plugin`:  mysql

##### Describe the bug
While trying to collect data from a MySQL table the following error is raised:
```shell
Uncaught exception: An error occurred while calling o56.save. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.sql.SQLException: Zero date value prohibited at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:99) at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:776) at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$makeGetter$2(JdbcUtils.scala:394) at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$makeGetter$2$adapted(JdbcUtils.scala:392) at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:361)
````

-------------------------------------------

##### This bug impact any demo or a sales?
-------------------------------------------
No

#### Dadosfera Customer:
-------------------------------------------
- duxnutritioncom

#### Pipeline ids:
- d1de8a6a_d35d_47ba_9913_4571466ec1fa

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@mariaeduaruda can you check with the customer if this is a useful pipeline for them?

**Comment by rafaelsantanaep** [comment]
The table that we're failing to capture is called:
´admin`.`duxdb_users´

**Comment by beatrizaantunes** [comment]
@mariaeduaruda did DUX answered you?

**Comment by rafaelsantanaep** [comment]
This error is also occurring for the mapa.
- `pipeline_id`:  2f5d4039_864a_4c5e_9277_c7ff67e7e714
- `job_id`: 2f5d4039_864a_4c5e_9277_c7ff67e7e714_8

@beatrizaantunes @cicerojmm @mariaeduaruda

**Comment by samirleao** [comment]
@cicerojmm 
A pipeline da Dux está deletada. Tentei investigar pela da MAPA, mas não estou conseguindo conectar na VPN deles. Só tomo timeout na hora de conectar na vpn, como se ela não estivesse up.

**Comment by samirleao** [comment]
Verifiquei que a pipeline da Mapa está falhando para coleta de todas as tabelas devido a um problema na vpn deles. Comuniquei os detalhes à Vanessa e ela está em comunicação com a mapa para averiguarem o serviço de vpn deles.

![Image](https://user-images.githubusercontent.com/11275599/213749464-d20abda9-4370-43c5-a978-56bd65c62212.png)
![Image](https://user-images.githubusercontent.com/11275599/213749463-acf43f78-6fb8-4ba0-acf7-4c1c32a54797.png)
![Image](https://user-images.githubusercontent.com/11275599/213749465-40d7c9b1-2bf0-4648-a575-6914ca0ae414.png)

**Comment by samirleao** [comment]
Aparentemente o problema da VPN foi resolvido hoje. Então podemos continuar com a investigação caso específico da Mapa aqui.

**Comment by samirleao** [comment]
O problema está ocorrendo pois nessa tabela (Candidate) temos algumas colunas do tipo DATETIME que estão com valor zero date (0000-00-00 00:00:00). O driver jdbc que faz a leitura dos dados não consegue interpretar este valor dessa forma pois é um valor inválido. Para lidar com isso, ele disponibiliza 3 comportamentos possíveis:

1) Levantar uma excessão (comportamento default e é o que está ocorrendo)
2) Arredondar (arredonda o valor zero date para o datetime válido mais próximo)
3) Converter para null (converte todos os valores zero date para null automaticamente)

Estou implementando o fix para este caso setando o comportamento 3, que julgo ser mais adequado. Ao utilizar os dados na Dadosfera (fazer queries e dashboards com os dados do DW), deve-se ter em mente a partir de agora a presença de colunas DATETIME com valor NULL, o que é mais fácil de detectar ou fazer comparações caso fosse o valor round por exemplo.

OBSERVAÇÃO: ESTA CONFIGURAÇÃO ESTÁ SENDO APLICADA APENAS PARA QUANDO O BANCO DE DADOS É MYSQL, POIS QUANDO PESQUISEI ENCONTREI ESSE PROBLEMA APENAS NO CONTEXTO DO MYSQL.

**Comment by samirleao** [comment]
PR pra lançamento em produção com a correção: https://github.com/dadosfera/jdbc-connector/pull/133/files

**Comment by samirleao** [comment]
Correção já lançada em produção.
