### ISSUE TITLE
Unable to process data from google sheets when the spreadsheet has been created using MS Excel and other tools

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#17]
##### There are customers are directly impacted by this bug. Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

#### Connector
- Singer

#### Pipeline Ids
- 79ae4f22_70a4_4b36_a5cf_2a5215999d27

#### Plugin
- Google Sheets

##### Describe the bug
While executing a pipeline with plugin `google-sheets`, the following error is raised:
```shell
HTTP-error-code: 400 {'code': 400, 'message': 'This operation is not supported for this document', 'status': 'FAILED_PRECONDITION'}: Unknown Error Traceback (most recent call last): File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/client.py", line 111, in raise_for_error response.raise_for_status() File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://sheets.googleapis.com/v4/spreadsheets/191O9Y_SANs1fRpC_QKFCf2I8j-11LR39?includeGridData=false&includeGridData=false During handling of the above exception, another exception occurred: Traceback (most recent call last): File ".meltano/extractors/tap-google-sheets/venv/bin/tap-google-sheets", line 8, in <module> sys.exit(main()) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/singer/utils.py", line 229, in wrapped return fnc(*args, **kwargs) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/__init__.py", line 51, in main do_discover(client, spreadsheet_id) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/__init__.py", line 26, in do_discover catalog = discover(client, spreadsheet_id) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/discover.py", line 6, in discover schemas, field_metadata = get_schemas(client, spreadsheet_id) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/schema.py", line 307, in get_schemas endpoint=stream_name) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/client.py", line 265, in get return self.request(method='GET', path=path, api=api, **kwargs) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry ret = target(*args, **kwargs) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry ret = target(*args, **kwargs) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/singer/utils.py", line 95, in wrapper return func(*args, **kwargs) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/client.py", line 259, in request raise_for_error(response) File "/app/.meltano/extractors/tap-google-sheets/venv/lib/python3.7/site-packages/tap_google_sheets/client.py", line 128, in raise_for_error raise ex(message) tap_google_sheets.client.GoogleBadRequestError: HTTP-error-code: 400 {'code': 400, 'message': 'This operation is not supported for this document', 'status': 'FAILED_PRECONDITION'}: Unknown Error
```

#### To Reproduce
1. Create a spreadsheet using MS Excel or a similar tool
2. Upload this spreadsheet to Google Sheets
3. Create a pipeline using the spreadsheet that you upload as a source
4. Executes the pipeline

This is a limitation of the Google Sheets API. Therefore, we should try to document this issue for the users, so they can convert their spreadsheet into a google spreadsheet before creating a pipeline.

#### How to detect if a spreadsheet was created by MS Excel
When a spreadsheet is created in MS Excel, it has the extension `xlsx` as you can see in the image below:
![image](https://user-images.githubusercontent.com/40280691/203210948-e776b4df-ace6-416c-aeeb-d1041b6a30ca.png)

#### How to convert a MS Excel Spreadsheet into a Google Spreadsheet:
1. Click on the menu `File`
2. Save as Google SpreadSheet

#### Dadosfera Customer:
-------------------------------------------
- dadosfera

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
This is already documented here @rafaelsantanaep : https://docs.dadosfera.ai/docs/google-sheets#par%C3%A2metros-para-configura%C3%A7%C3%B5es-da-pipeline
