### ISSUE TITLE
Airflow Killed a running task out of the blue

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#24]
##### There are customers are directly impacted by this bug? Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug
- While running a task, a SIGTERM was received and Airflow terminated the ECS Task that was running.
- By inspecting the metrics, it doesn't seem to be a resource limitation issue (memory, CPU).
- There wasn't any deploy on airflow today.

##### To Reproduce
Very difficult to reproduce

##### Expected behavior
-------------------------------------------
Airflow does not kill tasks unless this was triggered by an user

#### Dadosfera Customer:
-------------------------------------------
duxnutritioncom

#### pipeline_id
- 6ec85ea0_6eef_4d7f_abe8_9db0440804bb

## Other informations:

**Any logs, error output, etc?** …
```log
[2022-11-29, 17:00:10 UTC] {ecs.py:375} INFO - ECS task ID is: 049c4bf374284c7d9e6c263174e9d3f1
[2022-11-29, 18:55:02 UTC] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-11-29, 18:55:02 UTC] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 22384. PIDs of all processes in the group: [22384]
[2022-11-29, 18:55:02 UTC] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 22384
[2022-11-29, 18:55:02 UTC] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-29, 18:55:02 UTC] {ecs.py:513} INFO - {'task': {'attachments': [{'id': 'd3bb5502-63c5-48fb-832a-52dce82a4c9f', 'type': 'ElasticNetworkInterface', 'status': 'ATTACHED', 'details': [{'name': 'subnetId', 'value': 'subnet-086517bdb62a97ccf'}, {'name': 'networkInterfaceId', 'value': 'eni-0eaa8fe11a7aabf5c'}, {'name': 'macAddress', 'value': '0e:e4:ea:9d:2a:5f'}, {'name': 'privateDnsName', 'value': 'ip-13-0-2-30.ec2.internal'}, {'name': 'privateIPv4Address', 'value': '13.0.2.30'}]}], 'attributes': [{'name': 'ecs.cpu-architecture', 'value': 'x86_64'}], 'availabilityZone': 'us-east-1b', 'clusterArn': 'arn:aws:ecs:us-east-1:611330257153:cluster/dadosfera-prd', 'connectivity': 'CONNECTED', 'connectivityAt': datetime.datetime(2022, 11, 29, 17, 0, 13, 806000, tzinfo=tzlocal()), 'containers': [{'containerArn': 'arn:aws:ecs:us-east-1:611330257153:container/dadosfera-prd/049c4bf374284c7d9e6c263174e9d3f1/d20bbe1f-3f28-4951-bcd2-37515dc64df7', 'taskArn': 'arn:aws:ecs:us-east-1:611330257153:task/dadosfera-prd/049c4bf374284c7d9e6c263174e9d3f1', 'name': 'singer-prd', 'image': '611330257153.dkr.ecr.us-east-1.amazonaws.com/connectors/singer_prd:vtex', 'imageDigest': 'sha256:db4f7e7c5704de456fe4e3c24233e6048aaab0d18b1a3d12dbaab87c966ab620', 'runtimeId': '049c4bf374284c7d9e6c263174e9d3f1-3898084514', 'lastStatus': 'RUNNING', 'networkBindings': [], 'networkInterfaces': [{'attachmentId': 'd3bb5502-63c5-48fb-832a-52dce82a4c9f', 'privateIpv4Address': '13.0.2.30'}], 'cpu': '0'}], 'cpu': '4096', 'createdAt': datetime.datetime(2022, 11, 29, 17, 0, 10, 309000, tzinfo=tzlocal()), 'desiredStatus': 'STOPPED', 'enableExecuteCommand': False, 'group': 'family:singer-fargate-vtex-prd', 'lastStatus': 'RUNNING', 'launchType': 'FARGATE', 'memory': '24576', 'overrides': {'containerOverrides': [{'name': 'singer-prd', 'command': ['spark-submit', 'main.py', '{"job_id": "6ec85ea0_6eef_4d7f_abe8_9db0440804bb_0", "pipeline_id": "6ec85ea0_6eef_4d7f_abe8_9db0440804bb", "pipeline_run_id": "59b8b967e4f44164bd3e1636a731cabb"}']}], 'inferenceAcceleratorOverrides': []}, 'platformVersion': '1.4.0', 'platformFamily': 'Linux', 'pullStartedAt': datetime.datetime(2022, 11, 29, 17, 0, 20, 507000, tzinfo=tzlocal()), 'pullStoppedAt': datetime.datetime(2022, 11, 29, 17, 1, 24, 345000, tzinfo=tzlocal()), 'startedAt': datetime.datetime(2022, 11, 29, 17, 1, 43, 131000, tzinfo=tzlocal()), 'startedBy': 'airflow', 'stopCode': 'UserInitiated', 'stoppedReason': 'Task killed by the user', 'stoppingAt': datetime.datetime(2022, 11, 29, 18, 55, 2, 739000, tzinfo=tzlocal()), 'tags': [], 'taskArn': 'arn:aws:ecs:us-east-1:611330257153:task/dadosfera-prd/049c4bf374284c7d9e6c263174e9d3f1', 'taskDefinitionArn': 'arn:aws:ecs:us-east-1:611330257153:task-definition/singer-fargate-vtex-prd:10', 'version': 4, 'ephemeralStorage': {'sizeInGiB': 20}}, 'ResponseMetadata': {'RequestId': '33634ac9-c424-4aa4-a879-ff6fc6fe04df', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '33634ac9-c424-4aa4-a879-ff6fc6fe04df', 'content-type': 'application/x-amz-json-1.1', 'content-length': '2353', 'date': 'Tue, 29 Nov 2022 18:55:02 GMT'}, 'RetryAttempts': 0}}
[2022-11-29, 18:55:02 UTC] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 300, in execute
    self._start_wait_check_task(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 582, in decorator_f
    return fun(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 332, in _start_wait_check_task
    self._wait_for_task_ended()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 422, in _wait_for_task_ended
    waiter.wait(cluster=self.cluster, tasks=[self.arn])
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/waiter.py", line 54, in wait
    Waiter.wait(self, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/waiter.py", line 368, in wait
    time.sleep(sleep_amount)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")8
airflow.exceptions.AirflowException: Task received SIGTERM signal

```
What environment of software are you using?
- [x] PRD
- [ ] Other

**Browser Engine and Version:** …

**When the bug happened:** …
- Happened at 2022-11-29 16h55

**Comment by rafaelsantanaep** [comment]
FYI: @cicerojmm @beatrizaantunes

**Comment by samirleao** [comment]
I also was able to reproduce this problem on stg environment by executing a dag with a large number of tasks and a large value for parallelism. This is normally associated with lack of resources. By lowering the parallelism configuration on the dag i managed to execute it without problems. But it still can happen if there are a lot of tasks being executed at the same time. I think by crating a monitoring for Airflow we could pinpoint more easily if and when this problem is still happening and associate it lack of resources on one of airflow's component.

**Comment by beatrizaantunes** [comment]
Não voltou a acontecer e não é recorrente. Deixar no backlog como known issue
