### ISSUE TITLE
Snowflake Catalog DAG is not working since 05-12-2022

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#39]
##### There are customers directly impacted by this bug. Which?
-------------------------------------------
- All customers

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [x] Cataloging Data Asset
- [ ] Other

##### Describe the bug
The dag is failing to gather Praxio's secrets from Secrets Manager, but the customer_id id yet exists in the DUC.

Any views that depend on this dag to run properly will not be cataloged in production until this is solved.

##### Expected behavior
-------------------------------------------
- When the environment of a customer is deleted, the customer configuration is deleted from DUC.
- The airflow dag should ignore cases where it's not able to gather the Snowflake's secrets.

##### Screenshots
-------------------------------------------
![image](https://user-images.githubusercontent.com/40280691/207745340-9e0910b1-e2d2-44b0-b188-17340082da3a.png)

## Other information:

**Any logs, error output, etc?** …
```log
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-13T05:00:00+00:00
[2022-12-14, 05:00:26 UTC] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/snowflake_catalog.py", line 179, in get_endpoint_metadata
    snowflake_secret = get_secret_value(customer_name=customer)
  File "/opt/airflow/dags/snowflake_catalog.py", line 164, in get_secret_value
    response = client.get_secret_value(SecretId=secret_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the GetSecretValue operation: You can't perform this operation on the secret because it was marked for deletion.
````

What environment of software are you using?
- [x] PRD
- [ ] Other

**When the bug happened:** …
- It's happening every day

**Comment by rafaelsantanaep** [comment]
@cicerojmm @beatrizaantunes

**Comment by beatrizaantunes** [comment]
@alexsanderp @samirleao

**Comment by samirleao** [comment]
PR com o fix: https://github.com/dadosfera/airflow/pull/160/files

Já foi mergido, lançado e testado.
